### ISSUE TITLE
关于如何获取Android样本数据

### ISSUE THREAD

**Issue by bm-orange** [maoqyhz/DroidCC#1]
您好！
我是一名研二在读学生，由于目前准备开Android恶意应用检测方面的题目，正在为数据苦恼着，几乎好的数据集都需要发邮件，目前已给[VirusShare.com](https://virusshare.com/research.4n6)和[AndroMalShare](http://sanddroid.xjtu.edu.cn:8080/)发过邮件，但是以过去一周了，基本已被拒绝了。发现您的博文中做了一个有关Android恶意应用样本数据集的总结，感觉很棒，因此给您留言，希望可以交流一下。我也给您github的邮箱发过邮件，同时在您的博客下留言。
无论如何感谢您的分享！

**Comment by maoqyhz** [comment]
邮件已回复

**Comment by bm-orange** [comment]
十分感谢您的回复，同时非常谢谢您的建议，对我的帮助非常大，再次感谢您！

**Comment by Vinkki** [comment]
您好，我是一名研一在读研究生，目前在研究有关手机恶意软件的检测，如果方便的话可以发我一份数据集吗，邮箱18120370@bjtu.edu.cn,感激不尽！
