### ISSUE TITLE
代码中没有features.txt和sensitive_api.txt文件

### ISSUE THREAD

**Issue by xzgilhm** [maoqyhz/DroidCC#2]
作者，您好!
我是一名学生，我最近看您的代码，发现里面在进行特征提取的时候，缺少了features.txt和sensitive_api.txt两个文件。不知能否将这两个文件开源，非常感谢！

**Comment by maoqyhz** [comment]
特征请自行阅读论文总结以及对apk分析提取，这里暂时不公开，谢谢
