### ISSUE TITLE
Android 样本

### ISSUE THREAD

**Issue by Vinkki** [maoqyhz/DroidCC#3]
您好，我是一名研一在读学生，目前在看有关Android恶意软件检测的东西，想对您的工作做进一步了解，请问方便的话可以分享一下数据集吗，感激不尽

**Comment by Vinkki** [comment]
我的邮箱 18120370@bjtu.edu.cn

**Comment by ACGeny** [comment]
你好，我是来自合肥工业大学的一名在读研究生，我最近的研究的一个基金项目是关于安卓的恶意软件检测，我看了网上您的博客和您的相关工作，觉得很感兴趣，如果你能提供下您的数据集，关于恶意软件样本和良性样本，我将感激不尽，我的邮箱：bxd10001001@gmail.com。

**Comment by maoqyhz** [comment]
@ACGeny @Vinkki 我都发了

**Comment by maoqyhz** [comment]
@ACGeny 我博客里那个foxmail的邮箱是不是也是你，签名的id跟你一样的，

**Comment by ACGeny** [comment]
是的呀，一时着急需要数据，就两边都给你发邮件了，真的谢谢你啦~




------------------ 原始邮件 ------------------
发件人: "Qingyu Mao"<notifications@github.com>;
发送时间: 2019年5月28日(星期二) 晚上6:55
收件人: "maoqyhz/DroidCC"<DroidCC@noreply.github.com>;
抄送: "喜悦"<bxd1001001@foxmail.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [maoqyhz/DroidCC] Android 样本 (#3)




@ACGeny 我博客里那个foxmail的邮箱是不是也是你，签名的id跟你一样的，

**Comment by zscsg** [comment]
您好！我是贵州大学的一名博士研究生，最近要做一些和安卓恶意代码相关的工作需要用到Drebin数据集，我找原作者申请过数据集，无奈下载速度实在太慢，不知能否麻烦您分享一下Drebin数据集的相关内容。感激不尽！我的邮箱351625648@qq.com。

**Comment by ocloxz** [comment]
您好，我是山东理工大学的一名学生，最近在看有关安卓恶意软件的内容，无奈找不到数据集，不知能否麻烦您分享Drebin数据集的相关内容，实在感激不尽，我的邮箱是ocloxz00@gmail.com

**Comment by sunguohui1207** [comment]
你好，给您的outlook邮箱发了邮件，请求您的数据集，我是哈尔滨工程大学计算机学院研究生，现在在做安卓恶意软件检测的毕业论文，现急需数据集来完成论文的实验工作，如果您能提供您的数据集，我将十分感谢！
